# This is a basic workflow to help you get started with Actions

name: Trigger Netlify Build

on:
  schedule:
    - cron: '0 11 * * *'
    - cron: '0 17 * * *'

jobs:
  build:
    name: 'Request Netlify webhook'
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5f855b43e1b8a9adf2f72e05
